name: oh_snap_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  puppeteer: ^3.1.1
  dio: ^5.3.2
  retrofit: ^4.0.1
  json_annotation: any
  serverpod: ^1.1.1
  dotenv: ^4.1.0

dev_dependencies:
  lints: ^2.0.1
  retrofit_generator: any
  build_runner: any
  json_serializable: any